name: Generate and Validate Mihomo MRS Rules

on:
  schedule:
    - cron: '0 0 * * *'    # 每天00:00 UTC自动同步
  workflow_dispatch:        # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Clean old mrs file (保险，可选)
      run: rm -f data/rules/adblock.mrs

    - name: Generate MRS rules
      run: python data/python/generate_mrs.py

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Download Mihomo (linux-arm64, robust, jq)
      run: |
        set -e
        for i in 1 2 3; do
          url=$(curl -sSL "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest" \
            | jq -r '.assets[] | select(.name | test("linux-arm64.*gz$")) | .browser_download_url' | head -n1)
          echo "Download url: $url"
          if [ -n "$url" ] && wget -O mihomo-linux-arm64.gz "$url"; then
            break
          elif [ $i -eq 3 ]; then
            echo "Failed to download mihomo after 3 tries"
            echo "Raw API response:"
            curl -sSL "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest"
            exit 1
          fi
          sleep 2
        done
        gunzip -f mihomo-linux-arm64.gz
        BIN=$(ls | grep '^mihomo-linux-arm64' | grep -v '\.gz' | head -n1)
        if [ "$BIN" != "mihomo-linux-arm64" ]; then
          mv -f "$BIN" mihomo-linux-arm64
        fi
        chmod +x mihomo-linux-arm64
        ls -l mihomo-linux-arm64

    - name: Validate mrs rules with mihomo (retry 3 times)
      working-directory: data/rules
      run: |
        for i in 1 2 3; do
          if ../../mihomo-linux-arm64 -t -c check_config.yaml; then
            echo "Mihomo check passed"
            exit 0
          else
            echo "Mihomo check failed, retry $i/3"
            sleep 2
          fi
        done
        echo "Mihomo check failed after 3 attempts"
        exit 1

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'auto: update adblock.mrs'
        add: 'data/rules/adblock.mrs'