name: Generate and Validate Mihomo MRS Rules

on:
  schedule:
    - cron: '0 0 * * *'    # 每天00:00 UTC自动同步
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Clean old files
      run: rm -f data/rules/mihomo.txt

    - name: Generate merged rule txt
      run: python data/python/generate_mihomo_txt.py

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Download Mihomo (linux-amd64)
      run: |
        set -e
        url=$(curl -sSL "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest" \
          | jq -r '.assets[] | select(.name | test("linux-amd64.*gz$")) | .browser_download_url' | head -n1)
        echo "Download url: $url"
        wget -O mihomo-linux-amd64.gz "$url"
        gunzip -f mihomo-linux-amd64.gz
        BIN=$(ls | grep '^mihomo-linux-amd64' | grep -v '\.gz' | head -n1)
        if [ "$BIN" != "mihomo-linux-amd64" ]; then
          mv -f "$BIN" mihomo-linux-amd64
        fi
        chmod +x mihomo-linux-amd64
        ./mihomo-linux-amd64 -v

    - name: Convert mihomo.txt to adblock.mrs
      working-directory: data/rules
      run: |
        ../../mihomo-linux-amd64 mrs pack -i mihomo.txt -o adblock.mrs

    - name: Validate mrs rules with mihomo (retry 3 times)
      working-directory: data/rules
      run: |
        for i in 1 2 3; do
          if ../../mihomo-linux-amd64 -t -f check_config.yaml; then
            echo "Mihomo check passed"
            exit 0
          else
            echo "Mihomo check failed, retry $i/3"
            sleep 2
          fi
        done
        echo "Mihomo check failed after 3 attempts"
        exit 1

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'auto: update adblock.mrs'
        add: 'data/rules/adblock.mrs'
