name: Generate Mihomo MRS Rules

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'   # 每天00:00自动同步
  workflow_dispatch:       # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Generate MRS rules
      run: python data/python/generate_mrs.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions@github.com
        message: 'auto: update adblock.mrs'
        add: 'data/rules/adblock.mrs'