name: Generate Mihomo MRS Rules (Direct to MRS)

on:
  schedule:
    - cron: '0 0 * * *'    # 每天00:00 UTC自动同步
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Changes
        run: git pull

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget git jq

      - name: Download and install Mihomo
        run: |
          curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest \
            | jq -r '.assets[] | select(.name | test("linux-amd64.*\\.gz$")) | .browser_download_url' \
            | wget -q -O mihomo-linux-amd64.gz -i -
          gunzip -f mihomo-linux-amd64.gz
          chmod +x mihomo-linux-amd64

      - name: Download, Merge, and Deduplicate Rules
        run: |
          ADBLOCK_URLS='
          https://lingeringsound.github.io/10007_auto/adb.txt
          https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
          https://raw.hellogithub.com/hosts
          https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Replenish.txt
          https://raw.githubusercontent.com/qq5460168/666/master/rules.txt
          https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/master/SMAdHosts
          https://raw.githubusercontent.com/2771936993/HG/main/hg1.txt
          https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt
          https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
          '
          OUTPUT_TXT="data/rules/temp_rules.txt"
          mkdir -p "$(dirname "$OUTPUT_TXT")"
          rm -f "$OUTPUT_TXT"

          for url in $ADBLOCK_URLS; do
            echo "[*] Downloading: $url"
            curl -sSL "$url" >> "$OUTPUT_TXT"
            echo "" >> "$OUTPUT_TXT" # Add a newline between files
          done

          sort -u "$OUTPUT_TXT" -o "$OUTPUT_TXT"

          echo "[+] Merged and Deduplicated rules saved to $OUTPUT_TXT"

      - name: Convert to mrs
        working-directory: data/rules
        run: |
          ../../mihomo-linux-amd64 convert-ruleset domain text temp_rules.txt adblock.mrs

      - name: Delete temp file
        run: rm -f data/rules/temp_rules.txt

      - name: Get current date
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Moscow date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'auto: update adblock.mrs ${{ env.DATE }}'
          push: true
          cwd: .
          default_author: github_actions
          fetch: --tags --force
          pathspec_error_handling: ignore
          add: 'data/rules/adblock.mrs'
